### ISSUE TITLE
about nat

### ISSUE THREAD

**Issue by web3creator** [manishmeganathan/peerchat#5]
My nodes A and B are not in the same LAN. How can I send messages at this time?

**Comment by manishmeganathan** [comment]
@lmtwb
Well, I haven't gotten around to testing this on two independent networks yet.

But, the way libp2p works is that when we create the host object as shown below, by including the ``libp2p.NATPortMap()`` option, we are specifying that libp2p should open a port in the network firewall using UPnP (Universal Plug & Play). This should allow two nodes to discover each other on different networks because they announce their CID to the bootstrap peers using the Kademlia-DHT API. Refer to https://github.com/libp2p/go-libp2p/issues/300 for more context.
```go
// Construct a new LibP2P host with the multiaddr and the NAT Port Map
host, err := libp2p.New(
    ctx,
    libp2p.ListenAddrs(sourcemultiaddr),
    libp2p.NATPortMap(),
)
```

Also, UPnP needs to be enabled on the routers of both networks for this to work. This is a much easier thing to do than setting up port forwarding. Simply google it for your router model and you should be able to find some guide for it.

If you have tried to connect two nodes on different networks, please feel free to share your output/findings.

**Comment by web3creator** [comment]
@manishmeganathan I followed the instructions and still did not get through. Are you willing to help me? Support a completed case

**Comment by manishmeganathan** [comment]
@lmtwb 
I am working on some changes to the p2p setup runtime currently and we can start testing this application for connectivity across disparate networks. At this point, I can't promise that it WILL work, but it should according to libp2p docs, so the goal is to iron out any kinks. 
Can you tell me a little more about what you're trying to achieve? Are you using this repository directly or using it to work on your application?

**Comment by web3creator** [comment]
@manishmeganathan I build a simple chat application based on this repository, and my task is very interesting.

**Comment by manishmeganathan** [comment]
@lmtwb
Alright, how about you check back tomorrow. I'll update this thread when I've completed the refactor for the P2P setup runtime. Mostly involves #3 and #4. I also suspect that the lack of an identity key might be contributing to the inability of nodes on different networks to discover each other.
All this should be implemented overnight, and you can try that out and then let me know how it works for you. And if there are still some problems after that, we can work together to figure out what's wrong?

**Comment by web3creator** [comment]
@manishmeganathan 

`
impoert
        ci "github.com/libp2p/go-libp2p-core/crypto"
	peer "github.com/libp2p/go-libp2p-core/peer"
	peerstore "github.com/libp2p/go-libp2p-peerstore"
)

sk, pk, _ := ci.GenerateEd25519Key(rand.Reader)
skbytes, _ :=ci.PrivKey.Bytes()

ident.PrivKey = base64.StdEncoding.EncodeToString(skbytes)
id, _ := peer.IDFromPublicKey(pk).Pretty()
peerID, _ := peer.Decode(id)

peerstore.AddPubKey(peerID, sk.GetPublic())
peerstore.AddPrivKey(peerID, sk)

options = append([]libp2p.Option{libp2p.Identity(pkey), libp2p.Peerstore(ps))})
return libp2p.New(ctx, options...)
`

I am using a fixed ID generated in this way

**Comment by web3creator** [comment]
@manishmeganathan I use an iPhone to turn on the hotspot, and then the computer connects to this hotspot. I am on another computer connected to broadband, and the network of these two computers cannot be caht

**Comment by manishmeganathan** [comment]
@lmtwb 
Ah, that's the thing. That network configuration is never gonna work.
Let me break it down.
- First, the code you've used above is divergent from what's used here, we aren't maintaining an independent peerstore, the Kad DHT is doing that job for us, But there's nothing wrong with that approach. All you need to is add the ``libp2p.NATPortMap()`` option to the host constructor. It will end up looking like this
```go
return libp2p.New(ctx, libp2p.Identity(pkey), libp2p.Peerstore(ps), libp2p.NATPortMap())
```
- Secondly, your network configuration using your mobile phone as a hotspot is not going to work because in order for discovery to occur across different networks, the device must be able to punch a hole in the network firewall and configure the connection using UPnP. But, when you use a mobile device as a hotspot for a device, you are using the mobile as the router and using a mobile data connection for internet access, this is problematic because not all mobile hotspots support UPnP (not sure about iOS but I believe that is the general thing for mobile devices). So because your second node is connected to your mobile router (iPhone device), you need to first make sure that UPnP is enabled on it. I'm attaching a few links to figure that out. (P.S. The configuration of your ISP for your mobile data also factors into how UPnP support works).

https://www.askmefast.com/How_do_i_enable_upnp_on_iphone_personal_hotspot-qna4754535.html
https://www.connectify.me/blog/fix-internet/how-to-enable-upnp-on-mobile-hospot-to-play-games-online/

I would suggest that you try the different networks approach on two truly independent networks that both have full broadband routers with UPnP enabled on them.

**Comment by web3creator** [comment]
@manishmeganathan I wrote a case following your guide，He's here (https://github.com/lmtwb/libp2p_im.git)

`
cd cmd/server
go build main.go
Browser visit: http://127.0.0.1:3000/address, get the nat address

I had another computer：
cd cmd/client
go run main.go -a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

`

I still haven't solved it, I'm too stupid，My network has opened upnp

**Comment by manishmeganathan** [comment]
I'm actually really confused about what you're trying to achieve here. You shouldn't need to worry about the NAT address or any of that. Do you mind giving me a larger overview of the application

**Comment by web3creator** [comment]
@manishmeganathanI want to build a p2p communication app, so I need to solve this problem I encountered

**Comment by web3creator** [comment]
@manishmeganathan I want to achieve communication between different nat networks，I hope to realize real-time communication between me and the other end, but we are not under the same nat

**Comment by manishmeganathan** [comment]
@lmtwb 
Please check the current state of the repository. The latest release (**v1.1.0**) is capable of connecting nodes on two private networks as well. This is achieved by enabling the auto relay functionality of the libp2p host. The auto relay option requires you to set up a routing option as well, which means you need something like a Kademlia DHT to enable that.

Heres a snippet from the [*src/p2p.go*](https://github.com/manishmeganathan/peerchat/blob/754f74c6f523517ddb5e1841d98133fc91d835e8/src/p2p.go#L1) file. Note that the [``setupKadDHT``](https://github.com/manishmeganathan/peerchat/blob/754f74c6f523517ddb5e1841d98133fc91d835e8/src/p2p.go#L243) function is defined inside the *src/p2p.go* file and this entire snippet represents the body of the [``setupHost``](https://github.com/manishmeganathan/peerchat/blob/754f74c6f523517ddb5e1841d98133fc91d835e8/src/p2p.go#L161) function
```go
// Set up the host identity options
prvkey, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, rand.Reader)
identity := libp2p.Identity(prvkey)
// Handle any potential error
if err != nil {
    logrus.WithFields(logrus.Fields{
	"error": err.Error(),
    }).Fatalln("Failed to Generate P2P Identity Configuration!")
}

// Trace log
logrus.Traceln("Generated P2P Identity Configuration.")

// Set up TLS secured TCP transport and options
tlstransport, err := tls.New(prvkey)
security := libp2p.Security(tls.ID, tlstransport)
transport := libp2p.Transport(tcp.NewTCPTransport)
// Handle any potential error
if err != nil {
    logrus.WithFields(logrus.Fields{
	"error": err.Error(),
    }).Fatalln("Failed to Generate P2P Security and Transport Configurations!")
}

// Trace log
logrus.Traceln("Generated P2P Security and Transport Configurations.")

// Set up host listener address options
muladdr, err := multiaddr.NewMultiaddr("/ip4/0.0.0.0/tcp/0")
listen := libp2p.ListenAddrs(muladdr)
// Handle any potential error
if err != nil {
    logrus.WithFields(logrus.Fields{
	"error": err.Error(),
    }).Fatalln("Failed to Generate P2P Address Listener Configuration!")
}

// Trace log
logrus.Traceln("Generated P2P Address Listener Configuration.")

// Set up the stream multiplexer and connection manager options
muxer := libp2p.Muxer("/yamux/1.0.0", yamux.DefaultTransport)
conn := libp2p.ConnectionManager(connmgr.NewConnManager(100, 400, time.Minute))

// Trace log
logrus.Traceln("Generated P2P Stream Multiplexer, Connection Manager Configurations.")

// Setup NAT traversal and relay options
nat := libp2p.NATPortMap()
relay := libp2p.EnableAutoRelay()

// Trace log
logrus.Traceln("Generated P2P NAT Traversal and Relay Configurations.")

// Declare a KadDHT
var kaddht *dht.IpfsDHT
// Setup a routing configuration with the KadDHT
routing := libp2p.Routing(func(h host.Host) (routing.PeerRouting, error) {
    kaddht = setupKadDHT(ctx, h)
    return kaddht, err
})

// Trace log
logrus.Traceln("Generated P2P Routing Configurations.")

opts := libp2p.ChainOptions(identity, listen, security, transport, muxer, conn, nat, routing, relay)

// Construct a new libP2P host with the created options
libhost, err := libp2p.New(ctx, opts)
// Handle any potential error
if err != nil {
    logrus.WithFields(logrus.Fields{
	"error": err.Error(),
    }).Fatalln("Failed to Create the P2P Host!")
}
```

The primary factors that make inter-network communication work are the ``libp2p.EnableAutoRelay()`` option and the ``routing`` option that defines the **Kademlia DHT** and is used by the host for content routing and to discover relay nodes. I suggest you fully read the contents of the repository and perhaps try out this application to get a feel for how it works.

**Comment by manishmeganathan** [comment]
Feel free to let me know how the snippet above works out for you. 
I am closing this issue now.
