### ISSUE TITLE
Is there a way to create private bootstrap server?

### ISSUE THREAD

**Issue by zhenguang** [manishmeganathan/peerchat#6]
Is there a way to create private bootstrap server?

**Comment by manishmeganathan** [comment]
I haven't personally experimented on working with a private bootstrap server.
My understanding is that you can spin up a simple libp2p host with the kademlia DHT in bootstrap mode and then use its peer ID in your nodes instead of the DefaultBootstrapPeers from the kad-dht library.

**Comment by manishmeganathan** [comment]
There's also the fact that you need to make sure your bootstrap node is accessible to the public internet because with relays enabled, your peer would try to establish a direct connection to the bootstrap node and if it is hidden behind a NAT, it's not gonna be able to connect to it.
I'm happy to help if you already have a project that you're working on, let me know if there's anything else you'd like to know.
